[package]
name = "libsolv"
version = "0.1.0"
authors = ["Igor Gnatenko <ignatenko@redhat.com>"]

[workspace]
members = ["systest"]

[dependencies]
libsolv-sys = { path = "libsolv-sys" }
libsolvext-sys = { path = "libsolvext-sys" }
libc = "0.2"
clap = "2"